# Generated by Django 2.2.5 on 2019-11-09 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exicutive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='updated_at',
        ),
    ]
