# Generated by Django 2.2.5 on 2019-11-10 18:00

from django.db import migrations, models
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exicutive', '0002_auto_20191109_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='manager_table',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('manager_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='manager',
        ),
    ]
