# Generated by Django 2.2.5 on 2019-11-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myclients',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='myclients',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='myclients',
            name='updated_at',
        ),
    ]
